--------CAU 18----------
SELECT COUNT(*) AS N'Số lượng đề án'
FROM DEAN

--------CAU 19----------
SELECT TenPhg, TenDA
FROM NHANVIEN INNER JOIN PHONGBAN ON NHANVIEN.Phong = PHONGBAN.MaPhg INNER JOIN PHANCONG ON NHANVIEN.MaNV = PHANCONG.MaNV
INNER JOIN DEAN ON DEAN.MaDA = PHANCONG.MaDA
GROUP BY TenPhg, TenDA

--------CAU 20----------
SELECT COUNT(*) AS N'Số lượng phòng ban tham gia chủ trì',TenDA AS N'Tên đề án'
FROM NHANVIEN INNER JOIN PHONGBAN ON PHONGBAN.MaPhg = NHANVIEN.Phong INNER JOIN PHANCONG ON NHANVIEN.MaNV = PHANCONG.MaNV 
INNER JOIN DEAN ON DEAN.MaDA = PHANCONG.MaDA
GROUP BY TenPhg, TenDA

--------CAU 21----------
SELECT COUNT(DEAN.MADA) as 'Số lượng đề án'
FROM DEAN, PHONGBAN
WHERE DEAN.PHONG = PHONGBAN.MAPHG AND PHONGBAN.TENPHG = N'Nghiên cứu'

--------CAU 22----------
SELECT AVG(Luong) AS N'Lương trung bình'
FROM NHANVIEN
WHERE Phai LIKE N'Nữ'

--------CAU 23----------
SELECT (HoNV  + ' ' + TenLot + ' ' + TenNV) AS N'Họ Tên', TenTN AS N'Tên thân nhân'
FROM NHANVIEN, THANNHAN
WHERE NHANVIEN.MaNV = THANNHAN.MaNV AND HoNV = N'Đinh' AND TenLot = N'Bá' AND TenNV = N'Tiến'

--------CAU 24----------
SELECT (HoNV  + ' ' + TenLot + ' ' + TenNV) AS N'Họ Tên', YEAR(NgSinh)
FROM NHANVIEN
WHERE YEAR(NgSinh) < 1982
ORDER BY YEAR(NgSinh) ASC

--------CAU 25----------
SELECT DEAN.MaDA, SUM(PHANCONG.ThoiGian)
FROM NHANVIEN, PHANCONG, DEAN
WHERE NHANVIEN.MaNV = PHANCONG.MaNV AND PHANCONG.MaDA = DEAN.MaDA
GROUP BY DEAN.MaDA

--------CAU 26----------
SELECT DEAN.TenDA, SUM(PHANCONG.ThoiGian) AS N'Tổng thời gian'
FROM DEAN, PHANCONG
WHERE PHANCONG.MaDA = DEAN.MaDA
GROUP BY DEAN.TenDA

--------CAU 27----------
SELECT TenDA, COUNT(*) AS N'Số nhân viên Tham gia'
FROM PHANCONG, NHANVIEN, DEAN
WHERE NHANVIEN.MaNV = PHANCONG.MaNV AND PHANCONG.MaDA = DEAN.MaDA
GROUP BY TenDA

--------CAU 28----------
SELECT (HoNV  + ' ' + TenLot + ' ' + TenNV) AS N'Họ Tên', COUNT(*) AS N'Số lượng thân nhân'
FROM NHANVIEN, THANNHAN
WHERE NHANVIEN.MaNV = THANNHAN.MaNV
GROUP BY HoNV, TenLot, TenNV

--------CAU 29----------
SELECT (HoNV  + ' ' + TenLot + ' ' + TenNV) AS N'Họ Tên', COUNT(*) AS N'Số lượng đề án đã tham gia'
FROM NHANVIEN, PHANCONG
WHERE NHANVIEN.MaNV = PHANCONG.MaNV
GROUP BY HoNV, TenLot, TenNV

--------CAU 30----------
SELECT TenPhg, AVG(Luong) AS N'Lương trung bình'
FROM PHONGBAN, NHANVIEN
WHERE PHONGBAN.MaPhg = NHANVIEN.Phong
GROUP BY TenPhg

--------CAU 31----------
SELECT TenPhg, COUNT(*) AS N'Số lượng nhân viên'
FROM PHONGBAN, NHANVIEN
WHERE PHONGBAN.MaPhg = NHANVIEN.Phong	
GROUP BY TenPhg
HAVING AVG(Luong)>5200000

--------CAU 32----------
SELECT TenPhg, COUNT(*) AS N'Số lượng đề án'
FROM PHONGBAN, DEAN, NHANVIEN, PHANCONG
WHERE NHANVIEN.Phong = PHONGBAN.MaPhg AND NHANVIEN.MaNV = PHANCONG.MaNV AND DEAN.MaDA = PHANCONG.MaDA
GROUP BY TenPhg

--------CAU 33----------
SELECT TenPhg, (HoNV  + ' ' + TenLot + ' ' + TenNV) AS N'Họ Tên', COUNT(*) AS N'Số lượng đề án'
FROM PHONGBAN, NHANVIEN, DEAN
WHERE MaNV = TrPhg AND MaPhg = Phong
GROUP BY TenPhg, HoNV, TenLot, TenNV

--------CAU 34----------
SELECT TenDA, COUNT(PHANCONG.MaNV)
FROM DEAN, PHANCONG, NHANVIEN
WHERE DEAN.MaDA = PHANCONG.MaDA AND NHANVIEN.MaNV = PHANCONG.MaNV
GROUP BY DEAN.TenDA