 -----CAU 1-----
 CREATE TABLE TON(
	MaVT NVARCHAR(10) PRIMARY KEY,
	TenVT NVARCHAR(20),
	SoLuongVT INT
)
CREATE TABLE NHAP(
	SoHDN NVARCHAR(10) PRIMARY KEY,
	MaVT NVARCHAR(10) FOREIGN KEY REFERENCES TON(MaVT),
	SoLuongN INT,
	DonGiaN MONEY,
	NgayN SMALLDATETIME,
)
CREATE TABLE XUAT(
	SoHDX NVARCHAR(10) PRIMARY KEY,
	MaVT NVARCHAR(10) FOREIGN KEY REFERENCES TON(MaVT),
	SoLuongX INT,
	DonGiaX MONEY,
	NgayX SMALLDATETIME
)

INSERT INTO TON
VALUES ('111', N'Xi Măng', 200),
('222', N'Gạch Men', 320),
('333', N'Thép', 800),
('444', N'Ngói', 200),
('555', N'Sắt', 500)

INSERT INTO NHAP
VALUES ('123', '111', 300, 900000, '2021-10-15'),
('456', '333', 250, 4500000, '2022-6-22'),
('789', '555', 400, 3200000, '2022-11-11')

INSERT INTO XUAT
VALUES ('321', '222', 200, 1800000, '2022-11-28'),
('654', '444', 170, 3600000, '2023-1-15')

-----CAU 2-----
CREATE VIEW CAU2
AS
SELECT TON.MaVT,TenVT, SUM(SoLuongX*DonGiaX) AS 'Tien ban'
FROM XUAT INNER JOIN TON ON XUAT.MaVT=TON.MaVT
GROUP BY TON.MaVT,TenVT
----TEST----
SELECT * FROM CAU2

-----CAU 3-----
CREATE VIEW CAU3
AS
SELECT TON.TenVT, SUM(SoLuongX) AS 'Tong SL'
FROM XUAT INNER JOIN TON ON XUAT.MaVT=TON.MaVT
GROUP BY TON.TenVT
----TEST----
SELECT * FROM CAU3

-----CAU 4-----
CREATE VIEW CAU4
AS
SELECT TON.TenVT, SUM(SoLuongN) AS 'Tong SL'
FROM NHAP INNER JOIN TON ON NHAP.MaVT=TON.MaVT
GROUP BY TON.TenVT
----TEST----
SELECT * FROM CAU4

-----CAU 5-----
CREATE VIEW CAU5
AS
SELECT TON.MaVT,TON.TenVT,SUM(SoLuongN)-SUM(SoLuongX) +
SUM(SoLuongVT) AS tongton
FROM NHAP INNER JOIN TON ON NHAP.MaVT=TON.MaVT
INNER JOIN XUAT ON TON.MaVT=XUAT.MaVT
GROUP BY TON.MaVT,TON.TenVT
----TEST----
SELECT * FROM CAU5

-----CAU 6-----
CREATE VIEW CAU6
AS
SELECT TenVT
FROM TON
WHERE SoLuongVT = (SELECT MAX(SoLuongVT) FROM TON)
----TEST----
SELECT * FROM CAU6

-----CAU 7-----
CREATE VIEW CAU7
AS
SELECT TON.MaVT,TON.TenVT
FROM TON INNER JOIN XUAT ON TON.MaVT=XUAT.MaVT
GROUP BY TON.MaVT,TON.TenVT
HAVING SUM(SoLuongX)>=100
----TEST----
SELECT * FROM CAU7

-----CAU 8-----
CREATE VIEW CAU8
AS
SELECT MONTH(NgayX) AS N'Tháng xuất' , YEAR(NgayX) AS N'Năm xuất', SUM(SoLuongX) AS N'Tổng số lượng xuẩt'
FROM XUAT
GROUP BY XUAT.NgayX
----TEST----
SELECT * FROM CAU8

-----CAU 9-----
CREATE VIEW CAU9
AS
SELECT TON.MaVT, TON.TenVT, NHAP.SoLuongN, XUAT.SoLuongX, NHAP.DonGiaN, XUAT.DonGiaX, NHAP.NgayN, XUAT.NgayX
FROM TON INNER JOIN NHAP ON TON.MaVT=NHAP.MaVT
INNER JOIN XUAT ON TON.MaVT=XUAT.MaVT
GROUP BY TON.MaVT, TON.TenVT, NHAP.NgayN, XUAT.NgayX, NHAP.SoLuongN, XUAT.SoLuongX, NHAP.DonGiaN, XUAT.DonGiaX
----TEST----
SELECT * FROM CAU9